name: todo-project

services:
  db:
    container_name: todo-db
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - todo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 1s
      timeout: 1s
      retries: 45

  backend:
    container_name: todo-backend
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:${BACKEND_PORT}"
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy

  admin-ui:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_UI_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_UI_PASSWORD}
    ports:
      - "127.0.0.1:5050:80"
    volumes:
      - admin-ui-data:/var/lib/pgadmin

volumes:
  todo-db-data:
  admin-ui-data: